### ISSUE TITLE
Please remove the CSV and the pdf file

### ISSUE THREAD

**Issue by Logiksgesteuert** [MainTobias/Klasse3#2]
Please consider to remove the .csv file ( Labor09/Labor09_List/app/src/main/res/raw/schueler_15_16.csv ) and the pdf you don't have the copyright for.

**Comment by MainTobias** [comment]
Sorry cant seem to find the file you are talking about. Please consider providing a link to clarify which files you are talking about

**Comment by Logiksgesteuert** [comment]
My bad I still had a old link a classmate sent me ;)
